### ISSUE TITLE
How to use SPC56XX's IVORS?( soft interrupt )

### ISSUE THREAD

**Issue by snikeguo** [microwan/spc560bcxx-demos#1]
no supported？
![17 03 31 1908_1](https://cloud.githubusercontent.com/assets/20830435/24548092/e60e8348-1645-11e7-82db-88adc792771f.jpg)

![17 03 31 1908_2](https://cloud.githubusercontent.com/assets/20830435/24549295/3bd660f2-164b-11e7-9c78-fdecc9b7cb3e.jpg)

**Comment by microwan** [comment]
Hello ,

RLA & HAL have some vector management and Soft Interrupt (see ivor.s and boot.s in RLA or HAL)
if you download SPC5Studio , there is some applications examples in Application Wizard.

             Best regards
 
                               Erwan
